config/routes.rb
StolenBicycleRegistry::Application.routes.draw do
  match '/search', to: 'bicycles#index', via: 'get'
  devise_scope :user do
    match 'sign_in', to: 'devise/sessions#new', via: 'get'
    match 'sign_out', to: 'devise/sessions#destroy', via: 'get'
    match 'sign_up', to: 'registrations#new', via: 'get'
  end

  devise_for :users, :controllers => { :registrations => :registrations }

  resources :bicycles
  resources :users, only: [:show]

  match '/home' => 'static_pages#home', via: 'get'
  match '/about' => 'static_pages#about', via: 'get'
  match '/philosophy' => 'static_pages#philosophy', via: 'get'
  match '/faq' => 'static_pages#faq', via: 'get'
  match '/prevention' => 'static_pages#prevention', via: 'get'
  match '/links' => 'static_pages#links', via: 'get'
  match '/twitter' => 'static_pages#twitter', via: 'get'
  match '/rfid_tags' => 'static_pages#whitepaper', via: 'get'

  root 'static_pages#home'
end

app/models/bicycle.rb
class Bicycle < ActiveRecord::Base
  include Geography

  has_attached_file :photo,
                    styles: { medium: "250x250>",
                              thumb: "100x100>" },
                    default_url: "bike_:style.png"

  belongs_to :user

  validates :user_id, presence: true
  validates :date, presence: true
  validates :region, presence: true, inclusion: { in: Geography::PROVINCES + Geography::STATES }
  validates :city, presence: true
  validates :description, presence: true, length: { minimum: 30, maximum: 2000 }
  validates :size_type, :inclusion => { :in => %w( cm in ) }, allow_blank: true
  validates :serial, uniqueness: true, allow_nil: true, allow_blank: true
  validates_with StringYearValidator
  # validates :year, numericality: true, inclusion: { in: (0..2100) }, allow_nil: true
  before_save :convert_year

  def self.flexible_search(query)
    search_or_none(query, bicycle_scope(query))
  end

  def not_approved?
    !self.approved?
  end

private

  def convert_year
    year.to_s
  end

  def self.search_or_none(query, scope)
    stripped_query = strip_values(query)
    if stripped_query.present?
      fuzzy_search(stripped_query).where(scope)
    else
      Bicycle.none
    end
  end

  def self.bicycle_scope(query)
    if (query.class != String && query['recovered'] == '1')
      { hidden: false }
    else
      { hidden: false, recovered: false }
    end
  end

  def self.strip_values(query)
    if query.present? && query.class != String
      query.clone.delete_if { |k, v| v.blank? || v == '0' || v == '1' }
    else
      query
    end
  end
end

app/models/geography.rb
module Geography
  extend ActiveSupport::Concern

  STATES =  ['AL', 'AK', 'AZ', 'AR', 'CA', 'CO', 'CT', 'DE', 'FL', 'GA',
             'HI', 'ID', 'IL', 'IN', 'IA', 'KS', 'KY', 'LA', 'ME', 'MD',
             'MA', 'MI', 'MN', 'MS', 'MO', 'MT', 'NE', 'NV', 'NH', 'NJ',
             'NM', 'NY', 'NC', 'ND', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC',
             'SD', 'TN', 'TX', 'UT', 'VT', 'VA', 'WA', 'WV', 'WI', 'WY',
             'DC']
  PROVINCES = ['AB', 'BC', 'MB', 'NB', 'NL', 'NS', 'NT', 'NU', 'ON',
               'PE', 'QC', 'SK', 'YT']

  def self.included(base)
    base.validates :country, presence: true
    base.validates :city, presence: true
    base.validates :region, presence: true
    base.validates :region, :inclusion => { :in => Geography::STATES, :if => :in_us? }
    base.validates :region, :inclusion => { :in => Geography::PROVINCES, :if => :in_canada? } 
    base.validates :postal_code, :postal_code => true
  end

  def in_us?
    country == 'United States'
  end

  def in_canada?
    country == 'Canada'
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  include Geography
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :encrypted_password, presence: true
  validates :email, uniqueness: true 
  validates :phone1, format: { with: /\A[(]{0,1}[0-9]{3}[)]{0,1}[-\s\.]{0,1}[0-9]{3}[-\s\.]{0,1}[0-9]{4}\z/ }, allow_nil: true, allow_blank: true
  validates :phone2, format: { with: /\A[(]{0,1}[0-9]{3}[)]{0,1}[-\s\.]{0,1}[0-9]{3}[-\s\.]{0,1}[0-9]{4}\z/ }, allow_nil: true, allow_blank: true
  validates :postal_code, presence: true
  has_many :bicycles
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?
  after_filter :store_location

  def store_location
    if (request.fullpath != "/users/sign_in" &&
        request.fullpath != "/users/sign_up" &&
        request.fullpath != "/users/password" &&
        !request.xhr?)
      session[:previous_url] = request.fullpath
    end
  end

  def redirect_back_or(default)
    redirect_to(session[:previous_url] || default)
    session.delete(:previous_url)
  end

protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:account_update) do |u|
      u.permit(:first_name, :last_name, :country, :city, :region,
                   :postal_code, :phone1, :phone2, :email, :password,
                   :password_confirmation, :current_password, :first_name_public,
                   :last_name_public, :email_public)
    end
    devise_parameter_sanitizer.for(:sign_up) do |u|
      u.permit(:first_name, :last_name, :country, :city, :region,
                   :postal_code, :phone1, :phone2, :email, :password,
                   :password_confirmation, :first_name_public, :last_name_public,
                   :email_public)
    end
  end

  # def after_inactive_sign_up_path_for(user)
  #   previous_url = session[:previous_url]
  #   session.delete(:previous_url)
  #   user_path(user) || new_bicycle_path
  # end

  def after_sign_up_path_for(user)
    user_path(user)
  end

  def after_sign_in_path_for(user)
    user_path(user)
  end

  def after_sign_out_path_for(user)
    root_path
  end
end

app/controllers/bicycles_controller.rb
class BicyclesController < ApplicationController
  before_action :user_signed_in?
  skip_before_action :require_login, only: [:index]

  def index
    if params[:query]
      @bicycles = Bicycle.flexible_search(params[:query])
      @bicycles = @bicycles.paginate(page: params[:page],
                                   per_page: 10).
                          order('date DESC')
    end
  end

  def new
    if signed_in?
      @bicycle = Bicycle.new(region: current_user.region, city: current_user.city,
                                                   country: current_user.country)
    else
      redirect_to sign_in_path
    end
  end

  def create
    @bicycle = current_user.bicycles.new(bicycle_params)
    if @bicycle.save
      redirect_to bicycle_path(@bicycle)
    else
      render 'new'
    end
  end

  def edit
    @bicycle = Bicycle.find(params[:id])
  end

  def update
    @bicycle = Bicycle.find(params[:id])
    respond_to do |format|
      format.html do
        if @bicycle.update(bicycle_params)
          redirect_to bicycle_path(@bicycle)
        else
          render 'edit'
        end
      end
      format.js do
        @bicycle.update(bicycle_params)
        render nothing: true
      end
    end
  end

  def show
    @bicycle = Bicycle.find(params[:id])
  end

  def destroy
    @bicycle = Bicycle.find(params[:id])
    if current_user = @bicycle.user
      @bicycle.destroy
      redirect_to user_path(current_user)
    else
      redirect_to user_path(current_user), notice: 'Access denied!'
    end
  end

  private

  def bicycle_params
    params.require(:bicycle).permit(:date, :city, :region, :country, :postal_code,
                                    :serial, :verified_ownership, :police_report,
                                    :description, :reward, :year, :brand, :model,
                                    :color, :size, :size_type, :photo, :user_id,
                                    :recovered, :hidden)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  protected

  def after_update_path_for(user)
    user_path(user)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @user = current_user if user_signed_in?
  end

  def about
  end

  def philosophy
  end

  def faq
  end

  def prevention
  end

  def links
  end

  def whitepaper
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    unless current_user == @user
      flash[:alert] = "Access denied"
      redirect_back_or user_path
    end
  end
end

app/views/static_pages/about.html.erb
<% provide(:title, '| About') %>
<h1 class="center lead title">About</h1>
<hr>
<p class="lead">My name is Bryan. I am a systems administrator, database programmer, and mountain biker. I now live in Portland, OR.</p>
<p><em>I have had 5 bikes stolen in 9 years - plus a handful of beater bikes.</em></p>
<p>I hate idiots who steal other peoples' bikes.</p>
<p>I hated the fact that the world lacked an online resource to register and search for stolen bikes. So I built one.</p>
<p>I decided that the world needed a free, well-organized stolen bike registry. Something that biking enthusiasts, bike shops, police, and theft victims could all use with minumim hassle.
So I hacked together a modern, searchable database...
<h4>This is it.</h4></p>

app/views/static_pages/faq.html.erb
<% provide(:title, '| FAQ') %>
<div class="container">
  <h1 class="center lead title">FAQ</h1>
  <hr>

<p class="list-title lead"> Can I register my bike BEFORE it gets stolen?</p>

<p> Not yet. Right now I'd like to keep the focus on bikes that are known to be stolen. Some time in the future (perhaps when I land a grant?) I'd like to have pre-theft registration worked into the site, but for now it creates more problems than it solves.</p>

<p class="list-title lead"> You're in Portland, OR. How does the SBR help people in (INSERT YOUR CITY NAME HERE)?</p>

<p> It is true that a lot of my work now is taking place in Portland, since I'm making good contacts here, but this site is designed to cover all of the U.S. - and now Canada! Since listings are broken down by state, city, and zipcode, the database doesn't really care if you're in New York or Alaska. The SBR wants to act as a clearinghouse, and let any local-level efforts/coalitions/angry mobs use it for their own purposes, since they'll know what will work for their community the best.</p>

<p class="list-title lead"> Where the heck are serial numbers located on a bike?</p>

<p> Most bikes have the serial number stamped into the frame just below the crankshaft - see this diagram. If the bicycle is standing upright, as it normally does, the serial will be 'facing down' at the pavement - so you'll probably have to flip the bike over to read it.</p>

<p>However: Some manufacturers put serial numbers on the head tubes, or they stamp both a serial number and model number on the bike, adding to the confusion. If you bought the bike from a shop, check the recipt - some shops are including bike serials on their recipts as an extra identification measure.</p>

<p>The University of Texas At Austin has an excellent online guide to locating your bike's serial number found here.</p>

<p class="list-title lead"> How do you intend to make money on this site?</p>

<p> I don't. Seriously. The web hosting is cheap, and it only takes about 5 minutes out of my day to check new signups and approve new listings, so it isn't like I'm going broke from this effort. I just want to help people recover their stolen bikes.<p>

<p>If for some reason I start incurring a bunch of hosting fees or it ends up eating up too much time, I'll sign a few volunteers up to help me manage the signups, or get a sponsor. But right now it isn't about money.</p>

<p>If you'd like to donate a few bucks and help defray the costs, however, that would be great. Better yet - buy a sticker and help support the SBR! Or you can click the 'Buy Now' button here to send me a straight-up donation.</p>

<p class="list-title lead"> Do you accept donations?</p>

<p>YES! You can paypal any donation amount you want to send to: bhance@gmail.com - please put "StolenBicycleRegistry.com" in the memo.</p>

<p>All donations go right back into the site, be it via hosting fees, sticker production, or time spent to update the code and website.</p>

<p class="list-title lead"> I've got a great idea, why don't you (GREAT IDEA HERE)</p>

<p> I, too have some great ideas for this site. In fact, there are two major portions that aren't 'live' yet that I think will make people say 'Wow, that's a cool idea.' Right now I'm in the advertising and PR phase, so when I have a critical mass of bikes registered I'll flip the switch.
But I'd also love to hear your idea!</p>
</div>

app/views/static_pages/home.html.erb
<% provide(:title, '| Home') %>
<div class="container center">
  <div class="title center">
    <p class="banner-text">Stolen Bicycle Registry</p>
  </div>
  <p class="lead sign-in">A free resource to register and track stolen bicycles.</p>

  <div>
    <% if @user %>
      <%= form_tag search_path, method: 'get' do %>
        <%= hidden_field_tag name="query[city]", @user.city %>
        <%= hidden_field_tag name="query[region]", @user.region %>
        <%= submit_tag "See local listings for #{ @user.city }, #{ @user.region }",
            class: 'btn btn-info', id: 'region-search' %>
      <% end %>
    <% end %>
  </div>

  <div class="row">
    <div class='col-md-4 home-div'>
      <div class="home-info lead well use" rel='<%= new_user_registration_path %>'>
        <h3 class="lead aboutbox">Register!</h3>
        <div>
          <p class="hometext">Maybe you just had your bike stolen.</p>
          <p class="hometext">Maybe you're buying a used bike and want to run its serial number first.</p>
          <p class="hometext">Maybe you work for a bike shop and want to know if that trade-in is hot.</p>
          <%= image_tag "bicycle.png", :class => "img-responsive twitterlogo", id: 'bicycle-icon', :alt => "Register!" %>
        </div>
      </div>
    </div>

    <div class='col-md-4 home-div'>
      <div class="home-info lead well search" rel='<%= search_path %>'>
        <h3 class="lead aboutbox">Search</h3>
        <p class="hometext">The Stolen Bicycle Registry allows users to search through a database, report stolen bicycles, and stay up-to-date on a stolen bike's status.</p>
        <%= image_tag "magnifying_glass.png", :class => "img-responsive twitterlogo", id: 'search-icon', :alt => "Search!" %>
      </div>
    </div>

    <div class='col-md-4 home-div'>
      <div class="home-info lead well follow" rel='<%= twitter_path %>'>
        <h2 class="lead aboutbox">Follow</h2>
        <p class="hometext">Twitter is a great tool when it comes to locating stolen bikes.</p>
        <p class="hometext">Click to see if your city has its own Stolen Bike Registry Twitter feed.</p>
        <%= image_tag "twitter-bird.png", :class => "img-responsive twitterlogo", id: 'tweet-icon', :alt => "Follow us on Twitter!" %>
      </div>
    </div>
  </div>
</div>

app/views/static_pages/links.html.erb
<% provide(:title, '| Links') %>
<h1 class='lead title center'>Links</h1>
  <p>
    Every now and then I'll run across a link that needs more attention - it may be a good writeup on the
    bike theft problem, crime stats, or perhaps someone else who is doing something truly unique to try and
    help recover stolen bikes. I'm going to keep a running log here.
  </p>

  <p>
    There are also many people helping me out with this effort, and I'll try to list you all here,
    but forgive me if I leave some of you out. Feel free to click around and support the cause!
  </p>

  <h2 class ='list-title lead'>Localized registries</h2>
  <ul>
    <li><a href="http://stolenbikestacoma.com">Stolen Bikes Tacoma</a></li>
    <li><a href="http://www.missionstation.org/recovered-bicycles-in-the-mission.html">SFPD's Mission Station - Recovered Stolen Bicycles</a></li>
    <li><a href="http://bikesintheheights.org/resources/stolen-bikes/report-stolen-bicycle/">bikesintheheights.org - stolen bikes in Cleveland Heights, OH</a></li>
    <li><a href="http://www.atxbs.com/?q=aggregator/sources/1">ATXBS.com's stolen bikes in Austin, TX</a></li>
    <li><a href="http://tucsonvelo.com/category/stolen-bikes">TucsonVelo's stolen bikes in Tucson, AZ</a></li>
    <li><a href="http://chicago.stolenbike.org/">chicago.stolenbike.org - stolen bikesin Chicago, IL</a></li>
    <li><a href="http://www.missionstation.org/recovered-bicycles-in-the-mission.html">SFPD Mission Station - recovered bikes</a></li>
  </ul>

  <h2 class ='list-title lead'>General</h2>
  <ul>
    <li><a target=_new href="http://bicyclehabitat.com/site/page.cfm?PageID=139">10 Worst cities for bike theft</a></li>
    <li><a target=_new href="http://www.austinchronicle.com/issues/dispatch/1999-11-26/pols_feature.html">When It Comes to Bike Theft, Austin Is Tops</a></li>
  </ul>

  <h2 class ='list-title lead'>Bike Sites</h2>
  <ul>
    <li><a target="_new" href="http://www.cpic-cipc.ca/English/search.cfm">Canadian Police Information Centre's Stolen Vehicle & Bicycle serial search page</a></li>
    <li><a target=_new href="http://yaybikes.com">yaybikes.com</a></li>
    <li><a target=_new href="http://someonestolemybike.com">someonestolemybike.com</a></li>
    <li><a target=_new href="http://bikerescue.org">bikerescue.org</a></li>
    <li><a target=_new href="http://atxbs.com">atxbs.com</a></li>
    <li><a target=_new href="http://bikeportland.org">bikeportland.org</a></li>
  </ul>

  <h2 class ='list-title lead'>Sister Sites</h2>
  <ul>
  <li><a target=_new href="http://stolenguitarregistry.com">stolenguitarregistry.com</a> - Register your stolen guitars!</li>
  <li><a target=_new href="http://stolenmotorcycleregistry.com">stolenmotorcycleregistry.com</a> - originally started to keep people</li>
    from trying to register their motorcycles with the SBR.
  </ul>


  <p>
  <h2 class ='list-title lead'>Associates</h2>
  <ul>
    <li><a target=_new href="http://www.sprockettsrecycledbicycles.com">sprockettsrecycledbicycles.com</a></li>
    <li><a target=_new href="http://www.bikinglasvegas.com/">bikinglasvegas.com</a></li>
    <li><a target=_new href="http://www.twospoke.com/">twospoke.com</a></li>
    <li><a target=_new href="http://www.twbc.org">Tacoma Wheelmen's Bicycle Club</a></li>
    <li><a target=_new href="http://lincolnct.com/2008/10/01/theft/">Gary G's lincolnct.com</a></li>
    <li><a target=_new href="http://www.baitbike.com">Baitbike.com</a></li>
    <li><a target=_new href="http://www.considerbiking.org">Considerbiking.org</a></li>
    <li><a target=_new href="http://bikeseattle.org/">Bikeseattle.org</a></li>
    <li><a target=_new href="http://www.ebbc.org/">East Bay Bicycle Coalition</a></li>
    <li><a target=_new href="http://www.bbtc.net/">The Bonneville Bicycle Touring Club</a></li>
    <li><a target=_new href="http://www.oceancyclery.com">Ocean Cyclery</a></li>
    <li><a target=_new href="http://www.mobiuscycle.com/">mobiuscycle.com!</a></li>
    <li><a target=_new href="http://www.csrichards.com/">Chris Richards, Tucson wedding photographer and all-around biker-ninja</a></li>
    <li><a target=_new href="http://www.dirtragmag.com/web/news-article.php?ID=550">Dirtmag!</a></li>
    <li><a target=_new href="http://cazbike.com">Coalition of Arizona Bicyclists</a></li>
    <li><a target=_new href="http://oldskoolcycles.com/">Oldskoolcycles.com</a></li>
    <li><a target=_new href="http://bikeportland.org">BikePortland.org</a></li>
    <li><a target=_new href="http://www.fixedgeargallery.com">Fixed Gear Gallery</a></li>
    <li><a target=_new href="http://www.montlakebike.com/">Montlake Bicycle shop</a></li>
    <li><a target=_new href="http://www.bike2work.com/s_cruz/link.html">Bike to work!</a></li>
    <li><a target=_new href="http://www.sonic.net/~douglasi/rev/home.htm">A local S.F. bike registry run by Douglass McKenzie</a></li>
    <li><a target=_new href="http://www.crankmail.com/">crankmail.com</a> - the Voice of Cyclists in NorthEast Ohio</li>
    <li><a target=_new href="http://www.newcolonist.com">newcolonist.com</a> (see their <a href="http://www.newcolonist.com/workbike.html" target=_new>bikes at work</a> page)</li>
    <li><a target=_new href="http://www.drunkcyclist.com" target=_new>drunkcyclist.com</a></li>
    <li><a target=_new href="http://www.bicycleuniverse.info" target=_new>bicycleuniverse.info</a></li>
    <li><a target=_new href="http://www.bikeiowa.com">bikeiowa.com</a></li>
    <li><a target=_new href="http://bikagaba.org">bikagaba.org</a></li>
    <li><a target=_new href="http://cherba.com">cherba.com</a> (<a target=_new href="http://cherba.com/atmb/index.html">Trail adventures in Tucson</a>)</li>
    <li><a target=_new href="http://andyville.org">andyville.org</a></li>
  </ul>

  <h2 class ='list-title lead'>Theft Statistics</h2>

  <ul>
    <li>It is estimated that over 1.5 million bicycles are stolen every year. The FBI received reports of 504,000 bicycles stolen in 1995, but estimates that only <strong>one-third</strong> of all stolen bikes are reported to police.</li>
    <li>The 2000 FBI Uniform Crime Report shows the average price of a stolen bicycle is $276. With more than 313,469 bicycles reported stolen in 2000, consumers lost over $86 million.</li>
    <li>A 1994 study of bicycle theft on college campuses ... found that a four-year college student has a 53% chance of having their bike stolen.</li>
    <li>In the 92-93 school year, 11 bikes out of 100 on campuses were stolen.</li>
    <li><a target=_new href="http://www.bicyclesource.com/bike/theft/campus-theft.shtml">http://www.bicyclesource.com/bike/theft/campus-theft.shtml</a></li>
    <li><a href="http://www.popcenter.org/problems/bicycle_theft" target=_new>Popcenter.org's fantastic 'The Problem of Bicycle Theft' (2008)</a></li>
  </ul>

app/views/static_pages/philosophy.html.erb
<% provide(:title, '| Philosophy') %>
<div class="container">
<h1 class="center lead title">Philosophy</h1>
<hr>

  <p>Bike theft sucks - No matter who you are, you probably just wanted a nice solid bike to ride, and now someone has stolen it. Otherwise you wouldn't be reading this.
  Where I live, most bikes get stolen by people who come onto campus to steal a bike for quick drug money. They quickly sell them to a pawn shop or other 'grey-area' dealer within a few hours.</p>

  <p>Thus, most stolen bikes never leave town, and most just get resold and end back up on campus, lost among the masses.</p>

  <p>The situation where you live may be different, but the fact remains that it is too easy for people to steal and resell bikes, and too difficult to register and search for stolen bikes.</p>

  <h2 class="list-title lead">The Crux Of The Problem:</h2>

  <h4 class="lead"> There's no incentive to look for or report stolen bikes</h4>

  <p>Even if a pawnshop, bike shop, or potential buyer thinks your bike's stolen, there's no good reason for them to check your bike's serial number. Why? If they do find out your bike is stolen, there's really nothing in it for them - except they're losing the chance to get a cheap bike.</p>

  <h4 class="lead"> The current stolen bike registry is sorely lacking</h4>

  <p>There is an existing stolen bike registry - The National Bike Registry. They want you to pay to include your bike's serial number in their database.
  Let me reiterate that: They want you, someone who just had your bike stolen, to PAY THEM to include your serial number in their database. In my book, that's getting screwed twice.</p>

  <p>Not to mention the fact that the only people who have easy access to the NBR's database is law enforcement. So unless your bike gets recovered by a cop, its serial number probably won't ever get checked out.</p>

  <h4 class="lead"> There's no easy way for the common person to check a bike's serial number</h4>

  <p>Following right on the heels of #2, - there's no easy way for you or I, a bike shop, or a pawn shop, or ANYBODY to run serial numbers through the National Bike Registry. Sure, they can call the NBR's 1-800 number, get put on hold, and speak with a customer service rep. But that's a serious hassle.</p>

  <h2 class="list-title lead">Stolenbicycleregistry.com wants to help fix this</h2>
  <ul>
    <li>By providing FREE 5 year web-based registration for your stolen bike.</li>
    <li>By providing detailed, searchable bike info - including reward offers, photos of your stolen bike, and more.
    <li>By providing FREE web access to our stolen serial number database.</li>
    <li>By linking bike locators with bike owners.</li>
    <li>By running WATCHLIST - a free, bi-monthly email newsletter containing stolen bike info broken down by state, city, or zip code. WATCHLIST is printable, and aimed towards people who come into contact with a lot of bikes, and can act as a quick reference of all the stolen bicycles in a specific area.</li>
  </ul>

  <h2 class="list-title lead">Stolenbicycleregistry.com has a few other ideas ...</h2>

  <p>I've also put this <%= link_to "whitepaper", rfid_tags_path %></a> online, in which I outline a new approach to tackling the bike theft problem. Interested? Read Open Source Bike Recovery - On The Cheap.</p>
</div>

app/views/static_pages/twitter.html.erb
<% provide(:title, '| Twitter') %>
<div class="container">
  <div class="sign-in">
    <h1 class="twitter-header lead title center"> SBR Twitter Feeds </h1>
    <hr>
    <p class="lead center">If you're on Twitter and in one of these cities, please follow and retweet!</p>
  </div>
  <div class="row">
    <div class="twitter-links-page lead col-md-2 well col-md-offset-3">
      <h5>Regional Twitters</h5>
       <p class="twitter-links-page"><a href="https://twitter.com/stolenbikesbrk" target="_blank">Berkeley</a></p>
       <p><a href="https://twitter.com/stolenbikeschi" target="_blank">Chicago</a></p>
       <p><a href="https://twitter.com/stolenbikemarin" target="_blank">Marin County</a></p>
       <p><a href="https://twitter.com/stolenbikesphl" target="_blank">Philadelphia</a></p>
       <p><a href="https://twitter.com/stolenbikessan" target="_blank">San Diego</a></p>
       <p><a href="https://twitter.com/stolenbikessfo" target="_blank">San Francisco</a></p>
       <p><a href="https://twitter.com/stolenbikessea" target="_blank">Seattle</a></p>
       <p><a href="https://twitter.com/stolenbikestuc" target="_blank">Tucson</a></p>
    </div>
    <div class="col-md-4">
      <a class="twitter-timeline" href="https://twitter.com/stolenbikereg" data-widget-id="393137451402686464">Tweets by @stolenbikereg</a>
      <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
    </div>
  </div>
</div>