config/routes.rb
StolenBicycleRegistry::Application.routes.draw do
  match '/search', to: 'bicycles#index', via: 'get'
  devise_scope :user do
    match 'sign_in', to: 'devise/sessions#new', via: 'get'
    match 'sign_out', to: 'devise/sessions#destroy', via: 'get'
    match 'sign_up', to: 'registrations#new', via: 'get'
  end

  devise_for :users, :controllers => { :registrations => :registrations }

  resources :bicycles
  resources :users, only: [:show]

  match '/home' => 'static_pages#home', via: 'get'
  match '/about' => 'static_pages#about', via: 'get'
  match '/philosophy' => 'static_pages#philosophy', via: 'get'
  match '/faq' => 'static_pages#faq', via: 'get'
  match '/prevention' => 'static_pages#prevention', via: 'get'
  match '/links' => 'static_pages#links', via: 'get'
  match '/twitter' => 'static_pages#twitter', via: 'get'
  match '/rfid_tags' => 'static_pages#whitepaper', via: 'get'

  root 'static_pages#home'
end

app/models/bicycle.rb
class Bicycle < ActiveRecord::Base
  include Geography

  has_attached_file :photo,
                    styles: { medium: "250x250>",
                              thumb: "100x100>" },
                    default_url: "bike_:style.png"

  belongs_to :user

  validates :user_id, presence: true
  validates :date, presence: true
  validates :region, presence: true, inclusion: { in: Geography::PROVINCES + Geography::STATES }
  validates :city, presence: true
  validates :description, presence: true, length: { minimum: 30, maximum: 2000 }
  validates :size_type, :inclusion => { :in => %w( cm in ) }, allow_blank: true
  validates :serial, uniqueness: true, allow_nil: true, allow_blank: true
  validates_with StringYearValidator
  # validates :year, numericality: true, inclusion: { in: (0..2100) }, allow_nil: true
  before_save :convert_year

  def self.flexible_search(query)
    search_or_none(query, bicycle_scope(query))
  end

  def not_approved?
    !self.approved?
  end

private

  def convert_year
    year.to_s
  end

  def self.search_or_none(query, scope)
    stripped_query = strip_values(query)
    if stripped_query.present?
      fuzzy_search(stripped_query).where(scope)
    else
      Bicycle.none
    end
  end

  def self.bicycle_scope(query)
    if (query.class != String && query['recovered'] == '1')
      { hidden: false }
    else
      { hidden: false, recovered: false }
    end
  end

  def self.strip_values(query)
    if query.present? && query.class != String
      query.clone.delete_if { |k, v| v.blank? || v == '0' || v == '1' }
    else
      query
    end
  end
end

app/models/geography.rb
module Geography
  extend ActiveSupport::Concern

  STATES =  ['AL', 'AK', 'AZ', 'AR', 'CA', 'CO', 'CT', 'DE', 'FL', 'GA',
             'HI', 'ID', 'IL', 'IN', 'IA', 'KS', 'KY', 'LA', 'ME', 'MD',
             'MA', 'MI', 'MN', 'MS', 'MO', 'MT', 'NE', 'NV', 'NH', 'NJ',
             'NM', 'NY', 'NC', 'ND', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC',
             'SD', 'TN', 'TX', 'UT', 'VT', 'VA', 'WA', 'WV', 'WI', 'WY',
             'DC']
  PROVINCES = ['AB', 'BC', 'MB', 'NB', 'NL', 'NS', 'NT', 'NU', 'ON',
               'PE', 'QC', 'SK', 'YT']

  def self.included(base)
    base.validates :country, presence: true
    base.validates :city, presence: true
    base.validates :region, presence: true
    base.validates :region, :inclusion => { :in => Geography::STATES, :if => :in_us? }
    base.validates :region, :inclusion => { :in => Geography::PROVINCES, :if => :in_canada? } 
    base.validates :postal_code, :postal_code => true
  end

  def in_us?
    country == 'United States'
  end

  def in_canada?
    country == 'Canada'
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  include Geography
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :encrypted_password, presence: true
  validates :email, uniqueness: true 
  validates :phone1, format: { with: /\A[(]{0,1}[0-9]{3}[)]{0,1}[-\s\.]{0,1}[0-9]{3}[-\s\.]{0,1}[0-9]{4}\z/ }, allow_nil: true, allow_blank: true
  validates :phone2, format: { with: /\A[(]{0,1}[0-9]{3}[)]{0,1}[-\s\.]{0,1}[0-9]{3}[-\s\.]{0,1}[0-9]{4}\z/ }, allow_nil: true, allow_blank: true
  validates :postal_code, presence: true
  has_many :bicycles
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?
  after_filter :store_location

  def store_location
    if (request.fullpath != "/users/sign_in" &&
        request.fullpath != "/users/sign_up" &&
        request.fullpath != "/users/password" &&
        !request.xhr?)
      session[:previous_url] = request.fullpath
    end
  end

  def redirect_back_or(default)
    redirect_to(session[:previous_url] || default)
    session.delete(:previous_url)
  end

protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:account_update) do |u|
      u.permit(:first_name, :last_name, :country, :city, :region,
                   :postal_code, :phone1, :phone2, :email, :password,
                   :password_confirmation, :current_password, :first_name_public,
                   :last_name_public, :email_public)
    end
    devise_parameter_sanitizer.for(:sign_up) do |u|
      u.permit(:first_name, :last_name, :country, :city, :region,
                   :postal_code, :phone1, :phone2, :email, :password,
                   :password_confirmation, :first_name_public, :last_name_public,
                   :email_public)
    end
  end

  # def after_inactive_sign_up_path_for(user)
  #   previous_url = session[:previous_url]
  #   session.delete(:previous_url)
  #   user_path(user) || new_bicycle_path
  # end

  def after_sign_up_path_for(user)
    user_path(user)
  end

  def after_sign_in_path_for(user)
    user_path(user)
  end

  def after_sign_out_path_for(user)
    root_path
  end
end

app/controllers/bicycles_controller.rb
class BicyclesController < ApplicationController
  before_action :user_signed_in?
  skip_before_action :require_login, only: [:index]

  def index
    if params[:query]
      @bicycles = Bicycle.flexible_search(params[:query])
      @bicycles = @bicycles.paginate(page: params[:page],
                                   per_page: 10).
                          order('date DESC')
    end
  end

  def new
    if signed_in?
      @bicycle = Bicycle.new(region: current_user.region, city: current_user.city,
                                                   country: current_user.country)
    else
      redirect_to sign_in_path
    end
  end

  def create
    @bicycle = current_user.bicycles.new(bicycle_params)
    if @bicycle.save
      redirect_to bicycle_path(@bicycle)
    else
      render 'new'
    end
  end

  def edit
    @bicycle = Bicycle.find(params[:id])
  end

  def update
    @bicycle = Bicycle.find(params[:id])
    respond_to do |format|
      format.html do
        if @bicycle.update(bicycle_params)
          redirect_to bicycle_path(@bicycle)
        else
          render 'edit'
        end
      end
      format.js do
        @bicycle.update(bicycle_params)
        render nothing: true
      end
    end
  end

  def show
    @bicycle = Bicycle.find(params[:id])
  end

  def destroy
    @bicycle = Bicycle.find(params[:id])
    if current_user = @bicycle.user
      @bicycle.destroy
      redirect_to user_path(current_user)
    else
      redirect_to user_path(current_user), notice: 'Access denied!'
    end
  end

  private

  def bicycle_params
    params.require(:bicycle).permit(:date, :city, :region, :country, :postal_code,
                                    :serial, :verified_ownership, :police_report,
                                    :description, :reward, :year, :brand, :model,
                                    :color, :size, :size_type, :photo, :user_id,
                                    :recovered, :hidden)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  protected

  def after_update_path_for(user)
    user_path(user)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @user = current_user if user_signed_in?
  end

  def about
  end

  def philosophy
  end

  def faq
  end

  def prevention
  end

  def links
  end

  def whitepaper
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    unless current_user == @user
      flash[:alert] = "Access denied"
      redirect_back_or user_path
    end
  end
end

app/views/shared/_ca_regions_and_postals.html.erb
<div id='bicycle-ca-provinces'>
  <%= f.select :region, Geography::PROVINCES, :include_blank => 'Select Province' %>
</div>
<div class="input-group" id='bicycle-ca-postal'>
  <span class="input-group-addon label-info">Postal Code</span>
  <%= f.text_field :postal_code, placeholder: 'Zip/Postal Code', class: "form-control" %>
</div>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li>* <%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_google_ad.html.erb
<% unless Rails.env.test? %>
  <div class="google-ad">
    <script type="text/javascript"><!--
      google_ad_client = "pub-8815800758382772";
      /* 468x60, created 11/23/08 */
      google_ad_slot = "8923588004";
      google_ad_width = 468;
      google_ad_height = 60;
    </script>
    <script type="text/javascript"
    src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
    </script>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
<div class="navbar-header">
  <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
    <span class="sr-only">Toggle navigation</span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
  </button>
  <a class="navbar-brand" href="/home"><span class="glyphicon glyphicon-home"></span></a>
</div>

<div class="collapse navbar-collapse navbar-ex1-collapse">
  <ul class="nav navbar-nav">
    <li><%= link_to 'Register a bike', new_bicycle_path %></li>
    <li class="dropdown">

      <a href="#" class="dropdown-toggle" data-toggle="dropdown">Tools <b class="caret"></b></a>
      <ul class="dropdown-menu">
        <li><%= link_to 'Twitter', twitter_path %></li>
        <li><%= link_to "Bicycle Search", search_path %></li>
        <li role="presentation" class="divider"></li>
        <li><%= link_to 'About', about_path %></li>
        <li><%= link_to 'FAQ', faq_path %></li>
        <li><%= link_to 'Philosophy', philosophy_path %></li>
        <li><%= link_to 'Links', links_path %></li>
        <li><%= link_to 'Theft Prevention', prevention_path %></li>
      </ul>
    </li>
  </ul>

  <%= form_tag search_path, method: 'get', :class => 'navbar-form navbar-left' do %>
    <div class="form-group">
      <%= text_field_tag :query, nil, placeholder: 'simple search', :class => 'form-control' %>
    </div>
    <button type="submit" class="btn btn-default" id='basic-search'><span class="glyphicon glyphicon-search"></span></button>
  <% end %>
  <ul class="nav navbar-nav navbar-right">
    <li class="dropdown">
      <% if user_signed_in? %>
      <a href="#" class="dropdown-toggle" data-toggle="dropdown"> <%= current_user.email %> <b class="caret"></b></a>
      <ul class="dropdown-menu">
        <li><%= link_to "My Account", user_path(current_user) %></li>
        <li><%= link_to "Sign-out", sign_out_path %></li>
      <% else %>
        <li><%= link_to "Sign-in", sign_in_path %></li>
        <% end %>
      </ul>
    </li>
  </ul>
</div>
</nav>

app/views/shared/_us_regions_and_postals.html.erb
<div id='bicycle-us-states'>
  <%= f.select :region, Geography::STATES, :include_blank => 'Select State'%>
</div>
<div class="input-group" id='bicycle-us-zip'>
  <span class="input-group-addon label-info">Zip Code</span>
  <%= f.text_field :postal_code, placeholder: 'Zip Code', class: "form-control" %>
</div>