config/routes.rb
StolenBicycleRegistry::Application.routes.draw do
  match '/search', to: 'bicycles#index', via: 'get'
  devise_scope :user do
    match 'sign_in', to: 'devise/sessions#new', via: 'get'
    match 'sign_out', to: 'devise/sessions#destroy', via: 'get'
    match 'sign_up', to: 'registrations#new', via: 'get'
  end

  devise_for :users, :controllers => { :registrations => :registrations }

  resources :bicycles
  resources :users, only: [:show]

  match '/home' => 'static_pages#home', via: 'get'
  match '/about' => 'static_pages#about', via: 'get'
  match '/philosophy' => 'static_pages#philosophy', via: 'get'
  match '/faq' => 'static_pages#faq', via: 'get'
  match '/prevention' => 'static_pages#prevention', via: 'get'
  match '/links' => 'static_pages#links', via: 'get'
  match '/twitter' => 'static_pages#twitter', via: 'get'
  match '/rfid_tags' => 'static_pages#whitepaper', via: 'get'

  root 'static_pages#home'
end

app/models/bicycle.rb
class Bicycle < ActiveRecord::Base
  include Geography

  has_attached_file :photo,
                    styles: { medium: "250x250>",
                              thumb: "100x100>" },
                    default_url: "bike_:style.png"

  belongs_to :user

  validates :user_id, presence: true
  validates :date, presence: true
  validates :region, presence: true, inclusion: { in: Geography::PROVINCES + Geography::STATES }
  validates :city, presence: true
  validates :description, presence: true, length: { minimum: 30, maximum: 2000 }
  validates :size_type, :inclusion => { :in => %w( cm in ) }, allow_blank: true
  validates :serial, uniqueness: true, allow_nil: true, allow_blank: true
  validates_with StringYearValidator
  # validates :year, numericality: true, inclusion: { in: (0..2100) }, allow_nil: true
  before_save :convert_year

  def self.flexible_search(query)
    search_or_none(query, bicycle_scope(query))
  end

  def not_approved?
    !self.approved?
  end

private

  def convert_year
    year.to_s
  end

  def self.search_or_none(query, scope)
    stripped_query = strip_values(query)
    if stripped_query.present?
      fuzzy_search(stripped_query).where(scope)
    else
      Bicycle.none
    end
  end

  def self.bicycle_scope(query)
    if (query.class != String && query['recovered'] == '1')
      { hidden: false }
    else
      { hidden: false, recovered: false }
    end
  end

  def self.strip_values(query)
    if query.present? && query.class != String
      query.clone.delete_if { |k, v| v.blank? || v == '0' || v == '1' }
    else
      query
    end
  end
end

app/models/geography.rb
module Geography
  extend ActiveSupport::Concern

  STATES =  ['AL', 'AK', 'AZ', 'AR', 'CA', 'CO', 'CT', 'DE', 'FL', 'GA',
             'HI', 'ID', 'IL', 'IN', 'IA', 'KS', 'KY', 'LA', 'ME', 'MD',
             'MA', 'MI', 'MN', 'MS', 'MO', 'MT', 'NE', 'NV', 'NH', 'NJ',
             'NM', 'NY', 'NC', 'ND', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC',
             'SD', 'TN', 'TX', 'UT', 'VT', 'VA', 'WA', 'WV', 'WI', 'WY',
             'DC']
  PROVINCES = ['AB', 'BC', 'MB', 'NB', 'NL', 'NS', 'NT', 'NU', 'ON',
               'PE', 'QC', 'SK', 'YT']

  def self.included(base)
    base.validates :country, presence: true
    base.validates :city, presence: true
    base.validates :region, presence: true
    base.validates :region, :inclusion => { :in => Geography::STATES, :if => :in_us? }
    base.validates :region, :inclusion => { :in => Geography::PROVINCES, :if => :in_canada? } 
    base.validates :postal_code, :postal_code => true
  end

  def in_us?
    country == 'United States'
  end

  def in_canada?
    country == 'Canada'
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  include Geography
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :encrypted_password, presence: true
  validates :email, uniqueness: true 
  validates :phone1, format: { with: /\A[(]{0,1}[0-9]{3}[)]{0,1}[-\s\.]{0,1}[0-9]{3}[-\s\.]{0,1}[0-9]{4}\z/ }, allow_nil: true, allow_blank: true
  validates :phone2, format: { with: /\A[(]{0,1}[0-9]{3}[)]{0,1}[-\s\.]{0,1}[0-9]{3}[-\s\.]{0,1}[0-9]{4}\z/ }, allow_nil: true, allow_blank: true
  validates :postal_code, presence: true
  has_many :bicycles
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?
  after_filter :store_location

  def store_location
    if (request.fullpath != "/users/sign_in" &&
        request.fullpath != "/users/sign_up" &&
        request.fullpath != "/users/password" &&
        !request.xhr?)
      session[:previous_url] = request.fullpath
    end
  end

  def redirect_back_or(default)
    redirect_to(session[:previous_url] || default)
    session.delete(:previous_url)
  end

protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:account_update) do |u|
      u.permit(:first_name, :last_name, :country, :city, :region,
                   :postal_code, :phone1, :phone2, :email, :password,
                   :password_confirmation, :current_password, :first_name_public,
                   :last_name_public, :email_public)
    end
    devise_parameter_sanitizer.for(:sign_up) do |u|
      u.permit(:first_name, :last_name, :country, :city, :region,
                   :postal_code, :phone1, :phone2, :email, :password,
                   :password_confirmation, :first_name_public, :last_name_public,
                   :email_public)
    end
  end

  # def after_inactive_sign_up_path_for(user)
  #   previous_url = session[:previous_url]
  #   session.delete(:previous_url)
  #   user_path(user) || new_bicycle_path
  # end

  def after_sign_up_path_for(user)
    user_path(user)
  end

  def after_sign_in_path_for(user)
    user_path(user)
  end

  def after_sign_out_path_for(user)
    root_path
  end
end

app/controllers/bicycles_controller.rb
class BicyclesController < ApplicationController
  before_action :user_signed_in?
  skip_before_action :require_login, only: [:index]

  def index
    if params[:query]
      @bicycles = Bicycle.flexible_search(params[:query])
      @bicycles = @bicycles.paginate(page: params[:page],
                                   per_page: 10).
                          order('date DESC')
    end
  end

  def new
    if signed_in?
      @bicycle = Bicycle.new(region: current_user.region, city: current_user.city,
                                                   country: current_user.country)
    else
      redirect_to sign_in_path
    end
  end

  def create
    @bicycle = current_user.bicycles.new(bicycle_params)
    if @bicycle.save
      redirect_to bicycle_path(@bicycle)
    else
      render 'new'
    end
  end

  def edit
    @bicycle = Bicycle.find(params[:id])
  end

  def update
    @bicycle = Bicycle.find(params[:id])
    respond_to do |format|
      format.html do
        if @bicycle.update(bicycle_params)
          redirect_to bicycle_path(@bicycle)
        else
          render 'edit'
        end
      end
      format.js do
        @bicycle.update(bicycle_params)
        render nothing: true
      end
    end
  end

  def show
    @bicycle = Bicycle.find(params[:id])
  end

  def destroy
    @bicycle = Bicycle.find(params[:id])
    if current_user = @bicycle.user
      @bicycle.destroy
      redirect_to user_path(current_user)
    else
      redirect_to user_path(current_user), notice: 'Access denied!'
    end
  end

  private

  def bicycle_params
    params.require(:bicycle).permit(:date, :city, :region, :country, :postal_code,
                                    :serial, :verified_ownership, :police_report,
                                    :description, :reward, :year, :brand, :model,
                                    :color, :size, :size_type, :photo, :user_id,
                                    :recovered, :hidden)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  protected

  def after_update_path_for(user)
    user_path(user)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @user = current_user if user_signed_in?
  end

  def about
  end

  def philosophy
  end

  def faq
  end

  def prevention
  end

  def links
  end

  def whitepaper
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    unless current_user == @user
      flash[:alert] = "Access denied"
      redirect_back_or user_path
    end
  end
end

app/views/bicycles/_form.html.erb
<div class='well'>
  <div class='form-center'>
    <h1 class= 'lead title'>Bike Form</h1>
    <hr>
    <%= form_for @bicycle do |f| %>
    <h5>* = required</h5>
    <div class="input-group">
      <span class="input-group-addon label-info">Theft Date *</span>
      <%= f.text_field :date, id: 'datepicker', class: "form-control" %>
    </div>
    <div>
      <%= f.select :country, [ 'Canada', 'United States'], selected: @bicycle.country,
                   :include_blank => 'Select Country *', class: 'bicycle-country' %>
    </div>
    <div class="input-group">
      <span class="input-group-addon label-info">City *</span>
      <%= f.text_field :city, value: @bicycle.city, class: "form-control", autocomplete: "off",
                       'data-provide'=>'typeahead', 'data-source' => AutoComplete::CITIES %>
    </div>
    <div id="regions-and-postal-codes">
      <% if @bicycle.in_canada? %>
        <%= render 'shared/ca_regions_and_postals', f: f %>
      <% else %>
        <%= render 'shared/us_regions_and_postals', f: f %>
      <% end %>
    </div>

    <div class="input-group">
      <span class="input-group-addon label-info">Description *<span class='br'>
        <small>(Min 30 chars)</small></span></span>
      <%= f.text_area :description, placeholder: 'Minimum 30 char.', class: "form-control" %>
    </div>

    <div class="input-group">
      <span class="input-group-addon label-info">Serial</span>
      <%= f.text_field :serial, placeholder: 'PP123495877', class: "form-control" %>
    </div>

    <div class="input-group">
      <span class="input-group-addon label-info">Police File #</span>
      <%= f.text_field :police_report, placeholder: '1235463754', class: "form-control" %>
    </div>

    <div class="input-group">
      <span class="input-group-addon label-info">Year #</span>
      <%= f.text_field :year, placeholder: '2007', class: "form-control" %>
    </div>

    <div class="input-group">
      <span class="input-group-addon label-info">Brand</span>
      <%= f.text_field :brand, placeholder: 'Schwinn', class: "form-control", autocomplete: "off",
                       'data-provide'=>'typeahead', 'data-source' => AutoComplete::BRANDS %>
    </div>

    <div class="input-group">
      <span class="input-group-addon label-info">Model</span>
      <%= f.text_field :model, placeholder: 'Le Tour', class: "form-control" %>
    </div>

    <div class="input-group">
      <span class="input-group-addon label-info">Color</span>
      <%= f.text_field :color, placeholder: 'Simple colors!', class: "form-control", autocomplete: "off",
                       'data-provide'=>'typeahead', 'data-source' => AutoComplete::COLORS %>
    </div>

    <div class="input-group">
      <span class="input-group-addon label-info">Size</span>
      <%= f.text_field :size, placeholder: '27', class: "form-control" %>
    </div>

    <div>
      <%= f.select :size_type, ['cm', 'in'], :include_blank => 'Size | cm or in'  %>
    </div>

    <div class="input-group">
      <span class="input-group-addon label-info">Photo</span>
      <%= f.file_field :photo %>
    </div>

    <div>
      <%= f.select :verified_ownership, [['YES', true], ['NO', false]],
                   include_blank: 'Do you have proof of ownership?' %>
    </div>

    <div>
      <%= f.submit 'Register', class: 'btn btn-success' %>
    </div>
    <% end %>
  </div>
</div>

app/views/bicycles/edit.html.erb
<% provide(:title, '| Edit Bicycle') %>
<div id='errors'>
  <%= render 'shared/errors', object: @bicycle %>
</div>
<%= render 'form', object: @bicycle %>

app/views/bicycles/index.html.erb
<% provide(:title, '| Search') %>

<% if @bicycles %>
  <h3 class="highlight center"><%= pluralize(@bicycles.count, "search result") %>.</h3>
  <% if @bicycles.present? %>
    <div class="center">
      <%= will_paginate @bicycles, renderer: BootstrapPagination::Rails %>
    </div>
    <div class="table-responsive">
      <table class='table table-hover'>
        <tr>
          <td>Photo</td>
          <td>Stolen</td>
          <td>Year</td>
          <td>Color</td>
          <td>Brand</td>
          <td>Model</td>
          <td>City</td>
          <td>Region</td>
          <td>Country</td>
          <td>Serial</td>
        </tr>
        <% @bicycles.each do |bicycle| %>
          <tr>
            <td><a href=<%= bicycle_path(bicycle) %> >
              <%= image_tag bicycle.photo.url :thumb %>
            </a></td>
            <td><%= bicycle.date %></td>
            <td><%= bicycle.year %></td>
            <td><%= bicycle.color %></td>
            <td><%= bicycle.brand %></td>
            <td><%= bicycle.model %></td>
            <td><%= bicycle.city %></td>
            <td><%= bicycle.region %></td>
            <td><%= bicycle.country %></td>
            <td><%= bicycle.serial %></td>
          </tr>
        <% end %>
      </table>
    </div>
    <div class="center">
      <%= will_paginate @bicycles, renderer: BootstrapPagination::Rails %>
    </div>
  <% end %>
<% end %>

<div class="well">
  <%= form_tag search_path, :method => 'get', :class => "form-horizontal" do %>
    <div class="form-group">
      <h1 class='lead center'>Bicycle Search</h1>
      <div class="col-md-4 col-md-offset-2">
        <div class="input-group">
          <span class="input-group-addon label-info">Serial #</span>
          <%= text_field :query, :serial, placeholder: 'Serial #', class: "form-control" %>
        </div>
        <div class="input-group">
          <span class="input-group-addon label-info">Year</span>
          <%= number_field :query, :year, placeholder: 'Year', class: "form-control" %>
        </div>
        <div class="input-group">
          <span class="input-group-addon label-info">Brand</span>
          <%= text_field :query, :brand, placeholder: 'Make', class: "form-control", autocomplete: "off",
                         'data-provide'=>'typeahead', 'data-source' => AutoComplete::BRANDS %>
        </div>
        <div class="input-group">
          <span class="input-group-addon label-info">Model</span>
          <%= text_field :query, :model, placeholder: 'Model', class: "form-control" %>
        </div>
        <div class="input-group">
          <span class="input-group-addon label-info">Color</span>
          <%= text_field :query, :color, placeholder: 'Color', class: "form-control", autocomplete: "off",
                         'data-provide'=>'typeahead', 'data-source' => AutoComplete::COLORS %>
        </div>
      </div>
      
      <div class="col-md-4">
        <div class="input-group">
          <span class="input-group-addon label-info">Postal Code</span>
          <%= text_field :query, :postal_code, placeholder: 'Postal Code', class: "form-control" %>
        </div>

        <div class="input-group">
          <span class="input-group-addon label-info">City</span>
          <%= text_field :query, :city, value: user_signed_in? ? current_user.city : '',
                         placeholder: 'City', class: "form-control", autocomplete: "off", 'data-provide'=>'typeahead',
                        'data-source' => AutoComplete::CITIES %>
        </div>

        <div>
          <% if user_signed_in? && current_user.country == 'Canada' %>
            <%= select :query, :region, Geography::PROVINCES, :include_blank => 'Select Province',
                       selected: current_user.region %>
          <% elsif user_signed_in? && current_user.country == 'United States' %>
            <%= select :query, :region, Geography::STATES, :include_blank => 'Select Province',
                       selected: current_user.region %>
          <% else %>
            <%= select :query, :region, Geography::STATES + ['-Canada-'] + Geography::PROVINCES,
                       :include_blank => 'Select Province', :include_blank => 'Select Region' %>
          <% end %>
        </div>

        <div>
          <%= select :query, :country, ['United States', 'Canada'], :include_blank => 'Select Country', 
          selected: user_signed_in? ? current_user.country : 'Select Country' %>
        </div>

        <div="list-group">
          <span class="list-group-item">
          <%= check_box('query', 'recovered') %>
          <%= label(:recovered, "Include recovered bicycles") %>
          </span>
        </div>
      </div>
    <div class="center">
      <%= submit_tag 'Search', class: 'btn btn-small btn-success', id: 'advanced-search' %>
    </div>
    </div>
  <% end %>
</div>

app/views/bicycles/new.html.erb
<% provide(:title, '| Register') %>
<div id='errors'>
  <%= render 'shared/errors', object: @bicycle %>
</div>
<%= render 'form', object: @bicycle %>

app/views/bicycles/show.html.erb
<% provide(:title, '| Listing') %>
<h1 class="lead"> Stolen Bike Listing: </h1>
<div class='row container'>
  <a href="https://twitter.com/share"
     class="twitter-share-button"
     data-text="Help find this bike:"
     data-via="StolenBikeReg">
  </a>
  <% if user_signed_in? && current_user == @bicycle.user %>
      <p>
        <%= link_to 'Edit', edit_bicycle_path(@bicycle) %> |
        <%= link_to 'Delete', bicycle_path(@bicycle), method: 'delete', data: { confirm: "Are you sure you want to delete this listing?" } %> |
        <%= link_to 'My Account', user_path(@bicycle.user) %>
      </p>
  <% end %>
</div>
<div class="row">
  <div class='col-md-4'>
    <table class="table table-bordered">

      <% if @bicycle.hidden %>
        <tr>
          <td colspan='2', class='btn-danger center'>Listing is currently hidden.</td>
        </tr>
      <% end %>

      <tr>
        <td><%= image_tag @bicycle.photo.url :medium %></td>
      </tr>
      <tr>
        <td class='btn-info'>Description</td>
      </tr>
      <tr>
        <td><%= @bicycle.description %></td>
      </tr>
      <tr>
        <td align="center">
          <h3 class="lead">
            Have you seen me? Email us now if you have any info on my whereabouts.
          </h3>
          <a href="mailto:bhance@gmail.com" class="btn btn-success btn-lg">
           FOUND IT!
          </a>
        </td>
      </tr>
    </table>
  </div>

  <div class='col-md-8'>
    <table class="table table-bordered">
      <tr>
        <td colspan='2' class='btn-info'><strong>Theft Information</strong></td>
      </tr>
      <tr>
        <td>Theft Date:</td>
        <td><%= @bicycle.date %></td>
      </tr>
      <tr>
        <td>Location:</td>
        <td>
          <%= @bicycle.city %>,
          <%= @bicycle.region %>
          <%= @bicycle.postal_code %>
          <%= @bicycle.country %>
        </td>
      </tr>
      <tr>
        <td colspan='2' class='btn-info'><strong>Bicycle Information</strong></td>
      </tr>
      <tr>
        <td>Serial Number:</td>
        <td><strong><%= @bicycle.serial %></strong></td>
      </tr>
      <tr>
        <td>Year:</td>
        <td><%= @bicycle.year %></td>
      </tr>
      <tr>
        <td>Brand:</td>
        <td><%= @bicycle.brand %></td>
      </tr>
      <tr>
        <td>Model:</td>
        <td><%= @bicycle.model %></td>
      </tr>
      <tr>
        <td>Color:</td>
        <td><%= @bicycle.color %></td>
      </tr>
      <tr>
        <td>Size:</td>
        <td>
          <%= @bicycle.size %>
          <%= @bicycle.size_type %>
        </td>
      </tr>
      <tr>
        <td colspan='2' class='btn-info'><strong>Contact Information</strong></td>
      </tr>
      <tr>
        <td>First Name:</td>
        <td>
          <% if @bicycle.user.first_name_public %>
            <%= @bicycle.user.first_name %>
          <% else %>
            <p class="text-muted">private</p>
          <% end %>
        </td>
      </tr>
      <tr>
        <td>Last Name:</td>
        <td>
          <% if @bicycle.user.last_name_public %>
            <%= @bicycle.user.last_name %>
          <% else %>
            <p class="text-muted">private</p>
          <% end %>
        </td>
      <tr>
        <td>Email:</td>
        <td>
          <% if @bicycle.user.email_public %>
            <%= @bicycle.user.email %>
          <% else %>
            <p class="text-muted">Email not publicly available.</p>
            <p class="text-muted">Contact <a href="mailto:bhance@gmail.com">S.B.R. admin</a> with questions regarding this listing<p>
          <% end %>
        </td>
      </tr>
      <% if @bicycle.not_approved? %>
        <tr>
          <td colspan='2' class='btn-warning'><strong>Listing created at: <%= @bicycle.created_at %>, PENDING ADMIN APPROVAL.</strong></td>
        </tr>
      <% end %>
    </table>
  </div>
</div>